[plugin]
package = "pretix-secuconnect"
modules = [ "pretix_secuconnect" ]
marketplace_name = "secuconnect"
pypi = true
repository_servers = { origin = "github.com", gitlab = "code.rami.io" }
tag_targets = [ "origin", "gitlab" ]
branch_targets = [ "origin/master", "gitlab/master", "f:gitlab/pypi" ]

